[versions]
agp = "8.13.2"
kotlin = "2.0.21"
googleGmsGoogleServices = "4.4.2"

[libraries]
# (optional libs can stay, but not required for plugin fix)

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }